service: shopping-buddy-api

# Create an optimized package for our functions
package:
  individually: true

useDotenv: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

# These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: carts

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:us-east-2:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /carts
  # - method: POST request
  create:
    handler: create.main
    events:
      - http:
          path: carts
          method: post
  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /carts/{id}
    # - method: GET request
    handler: get.main
    events:
      - http:
          path: carts/{id}
          method: get
  list:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /carts
    # - method: GET request
    handler: list.main
    events:
      - http:
          path: carts
          method: get
  update:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /carts/{id}
    # - method: PUT request
    handler: update.main
    events:
      - http:
          path: carts/{id}
          method: put
  delete:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is /carts/{id}
    # - method: DELETE request
    handler: delete.main
    events:
      - http:
          path: carts/{id}
          method: delete
